name: 'Transfer'
description: 'package action from    https://github.com/Mikubill/transfer '
author: 'biner'
inputs:
  path:
    description: 'Directory containing files to upload'
    required: true
  platform:
    description: 'Backend Support:
  arp  -  Airportal  -  https://aitportal.cn/
  bit  -  bitSend  -  https://bitsend.jp/
  cat  -  CatBox  -  https://catbox.moe/
  cow  -  CowTransfer  -  https://www.cowtransfer.com/
  gof  -  GoFile  -  https://gofile.io/
  tmp  -  TmpLink  -  https://tmp.link/
  vim  -  Vim-cn  -  https://img.vim-cn.com/
  wss  -  WenShuShu  -  https://www.wenshushu.cn/
  wet  -  WeTransfer  -  https://wetransfer.com/
  flk  -  FileLink  -  https://filelink.io/
  trs  -  Transfer.sh  -  https://transfer.sh/
  lzs  -  Lanzous  -  https://www.lanzous.com/'
    required: true
  flags:
    description: 'Flags'
    required: false
outputs:
  uri:
    description: 'the uri '
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'archive'
  color: 'gray-dark'
